@baseUrl = http://localhost:3333/api

# @name Ping
GET {{baseUrl}}
Content-Type: application/json

###
# @name CreateUser
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJhMzBhYzYwNzI1MzQ3NTcyOGVlMDkiLCJpYXQiOjE2OTcyNjgwMTMsImV4cCI6MTY5NzM1NDQxM30.oOoBwpIGWrjWptBAjXVQqMACbJQ7kWMjMFXIJSTlgmw

{
  "username": "xxx da",
  "email": "hrxhr@me.com",
  "age": 18,
  "avatar": "https://i.pravatar.cc/150?img=50"
}

###
# @name GetUsers
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJhMzBhYzYwNzI1MzQ3NTcyOGVlMDkiLCJpYXQiOjE2OTcyNjgwMTMsImV4cCI6MTY5NzM1NDQxM30.oOoBwpIGWrjWptBAjXVQqMACbJQ7kWMjMFXIJSTlgmw

###
# @name UpdateUser
PUT {{baseUrl}}/users/652625545b2116f704967299
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJhMzBhYzYwNzI1MzQ3NTcyOGVlMDkiLCJpYXQiOjE2OTcyNjgwMTMsImV4cCI6MTY5NzM1NDQxM30.oOoBwpIGWrjWptBAjXVQqMACbJQ7kWMjMFXIJSTlgmw

{
  "username": "update username",
  "email": "updates@me.com",
  "age": 18,
  "avatar": "https://i.pravatar.cc/150?img=50"
}

###
# @name DeleteUser
DELETE {{baseUrl}}/users/652625545b2116f704967299
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJhMzBhYzYwNzI1MzQ3NTcyOGVlMDkiLCJpYXQiOjE2OTcyNjgwMTMsImV4cCI6MTY5NzM1NDQxM30.oOoBwpIGWrjWptBAjXVQqMACbJQ7kWMjMFXIJSTlgmw

###
# @name Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}

