@baseUrl = http://localhost:3333/api

# @name Ping
GET {{baseUrl}}
Content-Type: application/json

###
# @name Ping
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "xxx da",
  "email": "hrxhr@me.com",
  "age": 18,
  "avatar": "https://i.pravatar.cc/150?img=50"
}